# Практика №6 и №7— 03.12.2024 и 10.12.2024

# Упражнения на работу с pandas

In [ ]:
import pandas as pd
import numpy as np

## Упражнение № 1

Создайте Series из каждого из элементов: списка, ndarray и словаря.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

print(pd.Series(mylist))
print(pd.Series(myarr))
print(pd.Series(mydict))

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## Упражнение № 2

Преобразуйте `ser` в датафрейм с его индексом в качестве еще одного столбца датафрейма.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
```

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

# Преобразование значений Series в индексы DataFrame и наоборот
df = pd.DataFrame({'index': ser.index, 'value': ser.values})

print(df)

   index  value
0      a      0
1      b      1
2      c      2
3      e      3
4      d      4
5      f      5
6      g      6
7      h      7
8      i      8
9      j      9
10     k     10
11     l     11
12     m     12
13     n     13
14     o     14
15     p     15
16     q     16
17     r     17
18     s     18
19     t     19
20     u     20
21     v     21
22     w     22
23     x     23
24     y     24
25     z     25


## Упражнение № 3

Объедините `ser1` и `ser2`, чтобы сформировать датафрейм.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

df = pd.DataFrame({'col1' : pd.Series(mylist), 'col2' : pd.Series(myarr)})
print(df)

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25


## Упражнение № 4

Добавьте имя ряда  `ser`, назвав его `latin_letters`.

Пример входных данных:

```python
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
```

In [ ]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'latin_letters'
print(ser)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: latin_letters, dtype: object


## Упражнение № 5

Из `ser1` удалите элементы, присутствующие в `ser2`.

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

print(ser1[~ser1.isin(ser2)])


0    1
1    2
2    3
dtype: int64


## Упражнение № 6

Получить все элементы `ser1` и `ser2`, которые не являются общими для обоих рядов.

Пример входных данных:

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

print(pd.concat([ser1[~ser1.isin(ser2)], ser2[~ser2.isin(ser1)]]).reset_index(drop=True))

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64


## Упражнение № 7

Вычислите минимальное значение, 25-й процентиль, медиану, 75-й процентиль и максимальное значение `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.normal(10, 5, 25))
```

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))

print(f"Минимальное значение: {ser.min()}\n", f"25-й процентиль: {ser.quantile(0.25)}\n", f"Медиана: {ser.median()}\n", f"75-й процентиль: {ser.quantile(0.75)}\n", f"Максимальное значение: {ser.max()}")

Минимальное значение: -3.280812111847931
 25-й процентиль: 4.824573184577854
 Медиана: 7.509448577914154
 75-й процентиль: 14.593611747228993
 Максимальное значение: 17.232933928407174


## Упражнение № 8

Вычислите частоту встречаемости каждого уникального значения `ser`.

Пример входных данных:

```python
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser.value_counts(normalize=True))

c    0.166667
e    0.166667
d    0.133333
b    0.133333
g    0.133333
h    0.133333
a    0.066667
f    0.066667
Name: proportion, dtype: float64


## Упражнение № 9

Из `ser` оставить 2 наиболее часто встречающихся элемента без изменений, а все остальные заменить на `Прочее`.

Пример входных данных:

```python
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
```


In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

freq = ser.value_counts()
most_common = freq.index[:2]
print(ser.apply(lambda x: x if x in most_common else 'Прочее'))

0          2
1          3
2     Прочее
3          3
4          3
5          3
6          2
7     Прочее
8          3
9          2
10         2
11         3
dtype: object


# Упражнение № 10

Разбейте ряд `ser` на 10 равных децилей и замените значения на название дециля.

Пример входных данных:

```python
ser = pd.Series(np.random.random(20))
```

Пример выходных данных:

```python
# First 5 items
0    7th
1    9th
2    7th
3    3rd
4    8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]
```


In [ ]:
ser = pd.Series(np.random.random(20))

print(pd.qcut(ser, 10, labels=[f"Дециль_№{i+1}" for i in range(10)]))

0      Дециль_№2
1      Дециль_№1
2      Дециль_№3
3      Дециль_№7
4      Дециль_№2
5      Дециль_№8
6      Дециль_№3
7      Дециль_№9
8      Дециль_№4
9      Дециль_№4
10    Дециль_№10
11     Дециль_№9
12     Дециль_№5
13     Дециль_№7
14     Дециль_№8
15     Дециль_№6
16     Дециль_№5
17     Дециль_№1
18    Дециль_№10
19     Дециль_№6
dtype: category
Categories (10, object): ['Дециль_№1' < 'Дециль_№2' < 'Дециль_№3' < 'Дециль_№4' ... 'Дециль_№7' < 'Дециль_№8' < 'Дециль_№9' < 'Дециль_№10']


## Упражнение № 11

Переформируйте ряд `ser` в датафрейм с 7 строками и 5 столбцами

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 35))
```

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))

print(pd.DataFrame(ser.values.reshape(7, 5)))

   0  1  2  3  4
0  4  8  4  7  3
1  7  9  6  2  6
2  6  1  2  5  8
3  7  9  8  7  3
4  9  5  3  6  8
5  7  5  8  5  8
6  1  7  6  5  1


## Упражнение № 12

Найти позиции чисел, кратных 3, из ряда `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 7))
```


In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))

print("Серия:\n", ser)
print("Позиции чисел, кратных 3:", ser[ser % 3 == 0].index)

Серия:
 0    4
1    2
2    2
3    3
4    2
5    4
6    9
dtype: int32
Позиции чисел, кратных 3: Index([3, 6], dtype='int64')


## Упражнение № 13

Из `ser` извлечь элементы, находящиеся на позициях в списке `pos`.

Пример входных данных:

```python
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
```

In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

print(ser.take(pos))

0     a
4     e
8     i
14    o
20    u
dtype: object


## Упражнение № 14

Объедините `ser1` и `ser2` по вертикали и горизонтали (чтобы сформировать датафрейм).

Пример входных данных:

```python
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

df_horizontal = pd.concat([ser1, ser2], axis=1)
print("Объединение по горизонтали:\n", df_horizontal)

df_vertical = pd.concat([ser1, ser2], axis=0).reset_index(drop=True)
print("\nОбъединение по вертикали:\n", df_vertical)

Объединение по горизонтали:
    0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

Объединение по вертикали:
 0    0
1    1
2    2
3    3
4    4
5    a
6    b
7    c
8    d
9    e
dtype: object


## Упражнение № 15

Получите позиции элементов `ser2` в `ser1` в виде списка.

Пример входных данных:

```python
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
```

In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

print([int(ser1[ser1 == value].index[0]) for value in ser2])

[5, 4, 0, 8]


## Упражнение № 16

Вычислить среднеквадратическую ошибку рядов `truth` и `pred`.

Пример входных данных:

```python
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
```

In [ ]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

print(((truth - pred) ** 2).mean())

0.23894533935993195


## Упражнение № 17

В каждом слове `ser` поставьте первый символ каждого слова в верхний регистр.

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```


In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

print(ser.str.capitalize())

0     How
1      To
2    Kick
3    Ass?
dtype: object


## Упражнение № 18

В каждом слове `ser` посчитайте число символов.

Пример входных данных:

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

print(ser.apply(len))

0    3
1    2
2    4
3    4
dtype: int64


## Упражнение № 19

Вычислите разность разностей между последовательно идущими числами в `ser`.

Пример входных данных:

```python
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
```

Пример выходных данных:

```
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]
```

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print("Первая разность:\n", ser.diff().to_list())
print("Вторая разность:\n", ser.diff().diff().to_list())

Первая разность:
 [nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
Вторая разность:
 [nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


## Упражнение № 20

Преобразуйте строковое представление дат в `datetime64`.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil import parser
print(ser.apply(lambda x: parser.parse(x)))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


## Упражнение № 21

Получите из `ser` день месяца, номер недели, день года и день недели.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil import parser
ser_datetime = ser.apply(lambda x: parser.parse(x))
day_of_month = ser_datetime.dt.day.tolist()
week_number = ser_datetime.dt.isocalendar().week.tolist()
day_of_year = ser_datetime.dt.dayofyear.tolist()
day_of_week = ser_datetime.dt.day_name().tolist()

print("Номер дня в месяце:", day_of_month)
print("Номер недели:", week_number)
print("Номер дня в году:", day_of_year)
print("День недели:", day_of_week)

Номер дня в месяце: [1, 2, 3, 4, 5, 6]
Номер недели: [53, 5, 9, 14, 19, 23]
Номер дня в году: [1, 33, 63, 94, 125, 157]
День недели: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


## Упражнение № 22

Замените элементы `ser` на даты, начинающиеся с 4-го числа соответствующего месяца.

Пример входных данных:

```python
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
```

Пример выходных данных:

```
0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]
```

In [ ]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

from dateutil import parser
print(ser.apply(lambda x: parser.parse('04 ' + x)))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


## Упражнение № 23

Из `ser` извлеките слова, содержащие не менее 2 гласных букв.

Пример входных данных:

```python
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
```

Пример выходных данных:

```
0     Apple
1    Orange
4     Money
dtype: object
```

In [ ]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

def count_vowels(word):
    return sum(1 for char in word.lower() if char in 'aeiouy') 

print(ser[ser.apply(count_vowels) >= 2])

0     Apple
1    Orange
3    Python
4     Money
dtype: object


## Упражнение № 24

Извлеките корректные адреса электронной почты из ряда `emails`. Шаблон регулярного выражения для корректных адресов электронной почты приведен в качестве образца.

Пример входных данных:

```python
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
```

Пример выходных данных:

```
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object
```

In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

import re
print(emails[emails.apply(lambda x: re.match(pattern, x) is not None)])

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


## Упражнение № 25

Вычислить среднее значение веса в `weights` для каждого фрукта из `fruit`.

Пример входных данных:

```python
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
```

Пример выходных данных:

```python
# values can change due to randomness
apple     6.0
banana    4.0
carrot    5.8
dtype: float64
```

In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

print(weights.groupby(fruit).mean())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'carrot', 'banana', 'carrot', 'banana', 'carrot', 'banana', 'apple', 'apple', 'carrot']
apple     8.5
banana    5.0
carrot    4.6
dtype: float64


## Упражнение № 26

Вычислить [евклидово расстояние](https://en.wikipedia.org/wiki/Euclidean_distance) между векторами $p$ и $q$, не используя встроенную формулу.

Пример входных данных:

```python
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
```

Пример выходных данных:

```
18.165
```

In [ ]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

print("Евклидово расстояние:", np.sqrt(np.sum((p - q) ** 2)))

Евклидово расстояние: 18.16590212458495


## Упражнение № 27

Получите позиции пиков (значений, окруженных с двух сторон меньшими значениями) в `ser`.

Пример входных данных:

```python
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
```

Пример выходных данных:

```
array([1, 5, 7])
```

In [ ]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

print(np.where((ser.shift(1) < ser) & (ser.shift(-1) < ser)))

(array([1, 5, 7]),)


## Упражнение № 28

Замените пробелы в `my_str` на наименее часто встречающийся символ.

Пример входных данных:

```python
my_str = 'dbc deb abed gade'
```

Пример выходных данных:

```
'dbccdebcabedcgade'  # least frequent is 'c'
```

In [ ]:
my_str = 'dbc deb abed gade'

from collections import Counter
least_common_char = min(Counter(my_str.replace(' ', '')), key=Counter(my_str.replace(' ', '')).get) 
print(my_str.replace(' ', least_common_char))

dbccdebcabedcgade


## Упражнение № 29

Создайте временной ряд, начинающийся с `2000-01-01`, содержащий 10 субботних дней после этого и имеющий в качестве значений случайные числа

Пример выходных данных:

```
# values can be random
2000-01-01    4
2000-01-08    1
2000-01-15    8
2000-01-22    4
2000-01-29    4
2000-02-05    2
2000-02-12    4
2000-02-19    9
2000-02-26    6
2000-03-04    6
```


In [ ]:
date_range = pd.date_range(start='2000-01-01', periods=10, freq='W-SAT') # Субботушка 😄
random_values = np.random.randint(1, 10, size=10)
print(pd.Series(data=random_values, index=date_range))

2000-01-01    3
2000-01-08    7
2000-01-15    1
2000-01-22    5
2000-01-29    3
2000-02-05    6
2000-02-12    6
2000-02-19    8
2000-02-26    7
2000-03-04    1
Freq: W-SAT, dtype: int32


## Упражнение № 30

В `ser` отсутствуют некоторые даты и значения. Сделайте так, чтобы все отсутствующие даты появились и заполнились значением из предыдущей даты.

Пример входных данных:

```python
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
#> 2000-01-01     1.0
#> 2000-01-03    10.0
#> 2000-01-06     3.0
#> 2000-01-08     NaN
#> dtype: float64
```

Пример выходных данных:

```
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
```

In [ ]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

print(ser.resample('D').ffill())

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64


## Упражнение № 31

Вычислите автокорреляции для первых 10 лагов `ser`. Определите, какой из лагов имеет наибольшую корреляцию. (см. также [Модель авторегрессии и распределённого лага — Википедия](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C_%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D0%B8_%D0%B8_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BB%D0%B0%D0%B3%D0%B0))

Пример входных данных:

```python
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
```

Пример выходных данных:

```
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9
```

In [ ]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorrelations = [ser.autocorr(lag) for lag in range(1, 11)] 
max_lag = np.argmax(autocorrelations) + 1
autocorrelations = [float(corr) for corr in autocorrelations] 
print("Автокорреляции для первых 10 лагов:", autocorrelations)
print("Лаг с наибольшей корреляцией:", max_lag)

Автокорреляции для первых 10 лагов: [0.44395870762817, 0.14232079293152106, 0.22310416417208817, 0.0934659915388928, 0.40892798579625006, 0.4540558415252963, 0.41753808759642114, 0.13351470062169224, -0.7836226588028383, -0.2589561456769878]
Лаг с наибольшей корреляцией: 6


## Упражнение № 32

Импортируйте каждую 50-ю строку набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.


In [ ]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
print(pd.read_csv(url, skiprows=lambda x: x % 50 != 0))

      crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1  0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2  2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3  0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4  0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   
5  0.05561  70   2.24     0  0.400  7.041  10.0  7.8278    5  358     14.8   
6  0.02899  40   1.25     0  0.429  6.939  34.5  8.7921    1  335     19.7   
7  9.91655   0  18.10     0  0.693  5.852  77.8  1.5004   24  666     20.2   
8  7.52601   0  18.10     0  0.713  6.417  98.3  2.1850   24  666     20.2   
9  0.17783   0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   

        b  lstat  medv  
0  396.90  16.20  19.4  
1  396.90   6.19  33.2  
2  351.85  21.45  15.4  
3  396.90   4.56  34.9  
4  393.74   6.56

## Упражнение № 33

Импортируйте набор данных [boston housing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv), но при импорте измените столбец `'medv'` (*median house value*) так, чтобы значения < 25 стали `Low`, а > 25 - `High`.


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df['medv'] = df['medv'].apply(lambda x: 'Low' if x < 25 else 'High')
print(df.head()) # CSV-шка большая, выведем лишь немного

      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  


## Упражнение № 34

Создайте датафрейм со строками в виде шагов (интервалов) заданного ряда

Пример входных данных:

```python
L = pd.Series(range(15))
```

Пример выходных данных:

```
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])
```

In [ ]:
L = pd.Series(range(15))

def create_steps(series, step_size, window_size):
    return np.array([series[i: i + window_size] for i in range(0, len(series) - window_size + 1, step_size)])

print(pd.DataFrame(create_steps(L, step_size=2, window_size=4)))

    0   1   2   3
0   0   1   2   3
1   2   3   4   5
2   4   5   6   7
3   6   7   8   9
4   8   9  10  11
5  10  11  12  13


## Упражнение № 35

Импортируйте столбцы 'crim' и 'medv' из набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head()) # CSV-шка большая, выведем лишь немного

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


## Упражнение № 36

Получите количество строк, столбцов, тип данных и суммарную статистику каждого столбца набора данных [Cars93](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv). Также получите эквивалент датафрейма в виде numpy-массива и списка.


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

num_rows, num_columns = df.shape
data_types = df.dtypes
summary_stats = df.describe()

numpy_array = df.to_numpy()
list_data = df.values.tolist()

print(f'Количество строк: {num_rows}')
print(f'Количество столбцов: {num_columns}')
print('\nТипы данных каждого столбца:')
print(data_types)
print('\nСуммарная статистика каждого столбца:')
print(summary_stats)
print('\nЭквивалент DataFrame в виде numpy-массива:')
print(numpy_array)
print('\nЭквивалент DataFrame в виде списка:')
print(list_data)

Количество строк: 93
Количество столбцов: 27

Типы данных каждого столбца:
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object

Суммарная статистика каждого столбца:
       Min.Price      Price  Max.Price   MPG.city  MPG.highway

## Упражнение № 37

Извлеките номер строки и столбца конкретной ячейки по заданному критерию.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

*Какой производитель, модель и тип имеет наибольшую цену в `Price`? Каков номер строки и столбца ячейки с наибольшим значением `Price`?*


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

max_price = df['Price'].max()
max_price_rows = df[df['Price'] == max_price]
row_numbers = max_price_rows.index.tolist()
column_number = df.columns.get_loc('Price')

for row_number in row_numbers: # а вдруг их несколько
    manufacturer = df.at[row_number, 'Manufacturer']
    model = df.at[row_number, 'Model']
    car_type = df.at[row_number, 'Type']
    print(f'Производитель: {manufacturer}')
    print(f'Модель: {model}')
    print(f'Тип: {car_type}')
    print(f'Цена: {max_price}')
    print(f'Номер строки: {row_number}')
    print(f'Номер столбца: {column_number}')
    print('---')

Производитель: Mercedes-Benz
Модель: 300E
Тип: Midsize
Цена: 61.9
Номер строки: 58
Номер столбца: 4
---


## Упражнение № 38

Переименуйте в `df` столбец `Type` в `CarType` и замените `.` в именах столбцов на `_`.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
#> Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
#>        'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
#>        'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

Пример выходных данных:

```python
print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

df.rename(columns={'Type': 'CarType'}, inplace=True)
df.columns = df.columns.str.replace('.', '_')
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')
Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## Упражнение № 39

Проверьте, нет ли в `df` отсутствующих значений.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [ ]:

import io
import requests

data = requests.get('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv').text
data = data.replace(',"None",', ',"No_AirBags",') # Чертовы подушки -- если там none -- это не пустота, а отсутствие подушек, пустота -- NA.
df = pd.read_csv(io.StringIO(data))

print('Есть пропуски' if df.isnull().values.any() else 'Нет пропусков')

Есть пропуски


## Упражнение № 40

Подсчитайте количество пропущенных значений в каждом столбце `df`. Какой столбец имеет наибольшее число пропущенных значений?

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [ ]:
import io
import requests

data = requests.get('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv').text
data = data.replace(',"None",', ',"No_AirBags",') 
df = pd.read_csv(io.StringIO(data))

missing_values = df.isnull().sum()
max_missing_values = missing_values.max()
columns_with_max_missing = missing_values[missing_values == max_missing_values].index.tolist()
print("Количество пропущенных значений в каждом столбце:")
print(missing_values)
print("\nСтолб(ы) с наибольшим числом пропущенных значений:")
print(columns_with_max_missing)

Количество пропущенных значений в каждом столбце:
Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

Столб(ы) с наибольшим числом пропущенных значений:
['Luggage.room']


## Упражнение № 41

Замените отсутствующие значения в столбцах `Min.Price` и `Max.Price` на соответствующие им средние значения.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

avg_min_price = df['Min.Price'].mean()
avg_max_price = df['Max.Price'].mean()
df.fillna({'Min.Price' : avg_min_price}, inplace=True)
df.fillna({'Max.Price' : avg_max_price}, inplace=True)
print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


## Упражнение № 42

В `df` с помощью метода `apply` замените недостающие значения в `Min.Price` на среднее значение столбца, а в `Max.Price` — на медиану столбца.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

[Подсказка на StackOverflow](https://stackoverflow.com/questions/32437435/passing-additional-arguments-to-python-pandas-dataframe-apply)


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

def fill_missing_values(column):
    if column.name == 'Min.Price':
        return column.fillna(column.mean())
    elif column.name == 'Max.Price':
        return column.fillna(column.median())
    return column

df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(fill_missing_values)

print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000      18.80
1   29.200000      38.70
2   25.900000      32.30
3   17.118605      44.60
4   17.118605      19.15
..        ...        ...
88  16.600000      22.70
89  17.600000      22.40
90  22.900000      23.70
91  21.800000      23.50
92  24.800000      28.50

[93 rows x 2 columns]


## Упражнение № 43

Получите первый столбец (`a`) в `df` в виде датафрейма (а не в виде ряда).

Пример входных данных:

```python
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

print(df[['a']]) # или так print(pd.DataFrame(df['a']))

    a
0   0
1   5
2  10
3  15


## Упражнение № 44

1. В `df` поменяйте местами столбцы `'a'` и `'c'`.
2. Создайте обобщенную функцию для обмена данными между двумя столбцами без фиксированного задания имен столбцов.
3. Отсортируйте столбцы в обратном алфавитном порядке, т.е. от столбца `'e'` до столбца `'a'`.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

def swap_columns(dataframe, col1, col2):
    col1_data=dataframe[col1]
    col2_data=dataframe[col2]
    dataframe[col1]=col2_data
    dataframe[col2]=col1_data
    dataframe = dataframe.rename(columns={col1:col2, col2:col1})
    return dataframe

print("После замены столбцов 'a' и 'c':")
df = swap_columns(df, 'a', 'c')
print(df)

df = df[sorted(df.columns, reverse=True)]
print("\nПосле сортировки столбцов в обратном алфавитном порядке:")
print(df)

После замены столбцов 'a' и 'c':
    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

После сортировки столбцов в обратном алфавитном порядке:
    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15


## Упражнение № 45

Измените настройки отображения `pandas` при выводе на печать датафрейма `df`, чтобы он показывал максимум 10 строк и 10 столбцов.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Сохранение текущих настроек
original_max_rows = pd.get_option('display.max_rows')
original_max_columns = pd.get_option('display.max_columns')
# Изменение настроек отображения
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)
# Вывод DataFrame
print(df)
# Возврат настроек к значениям по умолчанию
pd.set_option('display.max_rows', original_max_rows)
pd.set_option('display.max_columns', original_max_columns)

   Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-U

## Упражнение № 46

Исключите вывод научной нотации типа 'e-03' в `df` и выведите до 4 чисел после запятой.

Пример входных данных:

```python
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df
#>          random
#> 0  3.474280e-03
#> 1  3.951517e-05
#> 2  7.469702e-02
#> 3  5.541282e-28
```

Пример выходных данных:

```python
#>    random
#> 0  0.0035
#> 1  0.0000
#> 2  0.0747
#> 3  0.0000
```

In [ ]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
print(df)
# Изменение настроек отображения
pd.set_option('display.float_format', '{:.4f}'.format)
# Вывод DataFrame
print(df)
# Возврат настроек к значениям по умолчанию
pd.reset_option('display.float_format')

         random
0  3.574157e-06
1  1.236636e-06
2  7.727031e-11
3  9.088724e-01
   random
0  0.0000
1  0.0000
2  0.0000
3  0.9089


## Упражнение № 47

Отформатируйте значения в столбце `'random'` из `df` в виде процентов.

Пример входных данных:

```python
df = pd.DataFrame(np.random.random(4), columns=['random'])
df
#>      random
#> 0    .689723
#> 1    .957224
#> 2    .159157
#> 3    .21082
```

Пример выходных данных:

```python
#>      random
#> 0    68.97%
#> 1    95.72%
#> 2    15.91%
#> 3    2.10%
```

In [ ]:

df = pd.DataFrame(np.random.random(4), columns=['random'])
print(df)

df['random'] = df['random'].apply(lambda x: f'{x * 100:.2f}%')
print(df)


     random
0  0.124941
1  0.196982
2  0.703630
3  0.401933
   random
0  12.49%
1  19.70%
2  70.36%
3  40.19%


## Упражнение № 48

Из `df` отфильтруйте значения `Manufacturer`, `Model` и `Type` для каждой 20-й строки, начиная с 1-й (строка 0).

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.loc[::20, ['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


## Упражнение № 49

В `df` замените `NaN` на `missing` в столбцах `Manufacturer`, `Model` и `Type` , создайте индекс как комбинацию этих трех столбцов и проверьте, является ли этот индекс первичным ключом.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
```

Пример выходных данных:

```
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN
```

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df['Index'] = df['Manufacturer'] + '_' + df['Model'] + '_' + df['Type']
df.set_index('Index', inplace=True)
is_unique = df.index.is_unique
print(df)
print(f"\nЯвляется ли индекс первичным ключом: {is_unique}")

                          Manufacturer    Model     Type  Min.Price  Max.Price
Index                                                                         
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6       22.7
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Mid

## Упражнение № 50

Найти положение строки с 5-м наибольшим значением столбца `'a'` в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10, -1), columns=list('abc'))
print(df)
print(f"Положение строки с 5-м наибольшим значением в столбце 'a': {df['a'].nlargest(5).index[-1]}")

    a   b   c
0  20   9  16
1  16  28  12
2  16  23   3
3   5  12  10
4  22  20  12
5  14  22  22
6  23  21  13
7  20  17  29
8   8  14  17
9  12  28  29
Положение строки с 5-м наибольшим значением в столбце 'a': 1



## Упражнение № 51

В `ser` найдите положение 2-го наибольшего значения, превышающего среднее.

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 100, 15))
```


In [ ]:
original_max_rows = pd.get_option('display.max_rows')
pd.set_option('display.max_rows', 100)

ser = pd.Series(np.random.randint(1, 100, 15))
print(ser)

mean_value = ser.mean()
filtered_values = ser[ser > mean_value]
second_largest_value = filtered_values.nlargest(2).iloc[-1]
position = ser[ser == second_largest_value].index[0] 

print(f"Среднее значение: {mean_value:.2f}")
print(f"Значения, превышающие среднее: {filtered_values.values}")
print(f"2-е наибольшее значение, превышающее среднее: {second_largest_value}")
print(f"Положение 2-го наибольшего значения, превышающего среднее: {position}")
pd.set_option('display.max_rows', original_max_rows)

0     35
1     68
2     72
3      7
4     63
5     27
6      2
7     50
8     43
9     28
10    52
11    79
12    87
13    26
14    27
dtype: int32
Среднее значение: 44.40
Значения, превышающие среднее: [68 72 63 50 52 79 87]
2-е наибольшее значение, превышающее среднее: 79
Положение 2-го наибольшего значения, превышающего среднее: 11


## Упражнение № 52

Получите две последние строки `df`, сумма строк которых больше 100.

```python
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [ ]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filtered_df = df[df.sum(axis=1) > 100] # строки больше сотки
print(filtered_df.tail(2))

     0   1   2   3
12  36  21  36  39
13  39  30  18  35


## Упражнение № 53

Замените все значения `ser`, находящиеся ниже 5%-ного и выше 95%-ного перцентиля, на соответствующие значения 5-го и 95-го перцентиля.

Пример входных данных:

```python
ser = pd.Series(np.logspace(-2, 2, 30))
```

In [ ]:
ser = pd.Series(np.logspace(-2, 2, 30))

percentile_5 = np.percentile(ser, 5)
percentile_95 = np.percentile(ser, 95)
ser = ser.apply(lambda x: percentile_5 if x < percentile_5 else (percentile_95 if x > percentile_95 else x))

print(ser)

0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
5      0.048939
6      0.067234
7      0.092367
8      0.126896
9      0.174333
10     0.239503
11     0.329034
12     0.452035
13     0.621017
14     0.853168
15     1.172102
16     1.610262
17     2.212216
18     3.039195
19     4.175319
20     5.736153
21     7.880463
22    10.826367
23    14.873521
24    20.433597
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.876672
dtype: float64


## Упражнение № 54

Перестройте `df` в максимально возможный квадрат с удалением отрицательных значений. При необходимости отбросьте наименьшие значения. Порядок положительных чисел в результате должен остаться тем же, что и в исходном варианте.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
```

In [ ]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10, -1))


positive_values = df[df >= 0].stack().reset_index(drop=True)
n = int(np.floor(np.sqrt(len(positive_values))))
positive_values = positive_values.nlargest(n*n).sort_index(kind='mergesort').reset_index(drop=True) # мергесорт каким-то образом оставляет порядок лучше других, особенно у одинаковых чисел с разными индексами
new_df = pd.DataFrame(positive_values.values.reshape(n, n))
print("Исходный DataFrame:")
print(df)
print("\nПреобразованный квадратный DataFrame:")
print(new_df)

Исходный DataFrame:
    0   1   2   3   4   5   6   7   8   9
0 -12  29  -2  28  37   8  41  37   2   2
1  44  10  42 -18   2 -15  14 -17   0  -2
2  46  10  16   3  36 -12  28 -18  29  39
3  13  40  -3  40  24  40   0  22  26   4
4   3  15  27  33 -20  21  15   2  45  31
5  -5  23   7 -20  32  24  34  49  15  36
6  33  29  -9  48 -20  34  -1  19  35  24
7 -16   4 -20  33  12  29 -18   7  27 -16
8 -11  37  20 -17  -3  38  17  -7 -14 -16
9  30   6 -14  -1  47  -7  14  30  -8 -19

Преобразованный квадратный DataFrame:
      0     1     2     3     4     5     6     7
0  29.0  28.0  37.0   8.0  41.0  37.0  44.0  10.0
1  42.0  14.0  46.0  10.0  16.0   3.0  36.0  28.0
2  29.0  39.0  13.0  40.0  40.0  24.0  40.0  22.0
3  26.0   4.0   3.0  15.0  27.0  33.0  21.0  15.0
4  45.0  31.0  23.0   7.0  32.0  24.0  34.0  49.0
5  15.0  36.0  33.0  29.0  48.0  34.0  19.0  35.0
6  24.0   4.0  33.0  12.0  29.0   7.0  27.0  37.0
7  20.0  38.0  17.0  30.0   6.0  47.0  14.0  30.0



## Упражнение № 55

Поменяйте местами строки 1 и 2 в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5, -1))
```

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

df.iloc[[1, 2]] = df.iloc[[2, 1]].values # про названия строк ничего не сказано, поэтому 😊
print(df)

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24



## Упражнение № 56

Переверните строки датафрейма `df` (первая строка становится последней).

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5, -1))
```

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print("Исходный DataFrame:")
print(df)
print("\nПеревернутый DataFrame:")
print(df.iloc[::-1]) 

Исходный DataFrame:
    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

Перевернутый DataFrame:
    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


## Упражнение № 57

Получите бинарный код для столбца `'a'` в датафрейме `df` и добавьте его в виде столбцов.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
```

Пример выходных данных:

```python
   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24
```

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1), columns=list('abcde'))

binary_cols = pd.get_dummies(df['a'], prefix='', prefix_sep='')
binary_cols.columns = [str(col) for col in binary_cols.columns]
binary_cols = binary_cols.astype(int) # избавляемся от тру фолз
df_binary = pd.concat([binary_cols, df.drop('a', axis=1)], axis=1)
print("Исходный DataFrame:")
print(df)
print("\nDataFrame с бинарным кодом:")
print(df_binary)

Исходный DataFrame:
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

DataFrame с бинарным кодом:
   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


## Упражнение № 58

Получите название столбца с наибольшим количеством строчных максимумов в `df`.

```python
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1))

max_columns = df.idxmax(axis=1)
max_count = max_columns.value_counts()
max_column_name = max_count.idxmax()
print("Исходный DataFrame:")
print(df)
print("\nНазвание столбца с наибольшим количеством строчных максимумов:", max_column_name)

Исходный DataFrame:
    0   1   2   3
0   6  22  19  40
1  55   4  84  79
2  19  97  27  42
3  21  87  68  58
4  68  81  77  70
5  14   6  66  24
6  58  48  61  59
7  40  15  90  11
8  62  98  31  95
9  86  70  84  18

Название столбца с наибольшим количеством строчных максимумов: 2


## Упражнение № 59

Создать новый столбец, в каждой строке которого будет указан номер строки, ближайшей по евклидову расстоянию к данной строке.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df
#     p   q   r   s
# a  57  77  13  62
# b  68   5  92  24
# c  74  40  18  37
# d  80  17  39  60
# e  93  48  85  33
# f  69  55   8  11
# g  39  23  88  53
# h  63  28  25  61
# i  18   4  73   7
# j  79  12  45  34
```

Пример выходных данных:

```python
df
#    p   q   r   s nearest_row   dist
# a  57  77  13  62           i  116.0
# b  68   5  92  24           a  114.0
# c  74  40  18  37           i   91.0
# d  80  17  39  60           i   89.0
# e  93  48  85  33           i   92.0
# f  69  55   8  11           g  100.0
# g  39  23  88  53           f  100.0
# h  63  28  25  61           i   88.0
# i  18   4  73   7           a  116.0
# j  79  12  45  34           a   81.0
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
print("Исходный DataFrame:")
print(df)

def euclidean_distance(row1, row2):
    return np.sqrt(np.sum((row1 - row2) ** 2))

nearest_rows = []
distances = []

for i, row1 in df.iterrows():
    min_distance = float('inf')
    nearest_row = None
    for j, row2 in df.iterrows():
        if i != j:
            dist = euclidean_distance(row1, row2)
            if dist < min_distance:
                min_distance = dist
                nearest_row = j
    nearest_rows.append(nearest_row)
    distances.append(min_distance)

df['nearest_row'] = nearest_rows
df['dist'] = distances


print("\nDataFrame с ближайшими строками и расстояниями:")
print(df)

Исходный DataFrame:
    p   q   r   s
a  47  69  64  62
b  37  10  66  35
c  25  77  19  67
d  43  73  89  49
e  73  39  16  87
f   2  64   5  71
g  71  89  87  33
h  91  73  80  59
i  38  82  11  73
j  94   7  83  62

DataFrame с ближайшими строками и расстояниями:
    p   q   r   s nearest_row       dist
a  47  69  64  62           d  28.740216
b  37  10  66  35           j  65.391131
c  25  77  19  67           i  17.146428
d  43  73  89  49           a  28.740216
e  73  39  16  87           i  57.402091
f   2  64   5  71           c  30.166206
g  71  89  87  33           d  36.055513
h  91  73  80  59           g  37.161808
i  38  82  11  73           c  17.146428
j  94   7  83  62           b  65.391131


## Упражнение № 60

Вычислите максимально возможное абсолютное значение корреляции каждого столбца с другими столбцами в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

correlation_matrix = df.corr()
max_absolute_correlation = correlation_matrix.apply(lambda x: x.abs().nlargest(2).iloc[1])

print("Корреляционная матрица:")
print(correlation_matrix)
print("\nМаксимально возможное абсолютное значение корреляции для каждого столбца (исключая себя):")
print(max_absolute_correlation)

Корреляционная матрица:
          p         q         r         s         t         u         v  \
p  1.000000 -0.868545  0.178023  0.274328  0.013773 -0.021794 -0.229086   
q -0.868545  1.000000 -0.088027 -0.104310 -0.084828  0.066360 -0.006605   
r  0.178023 -0.088027  1.000000 -0.026117  0.133732  0.888008 -0.003681   
s  0.274328 -0.104310 -0.026117  1.000000  0.823132 -0.428572 -0.212648   
t  0.013773 -0.084828  0.133732  0.823132  1.000000 -0.252966  0.049284   
u -0.021794  0.066360  0.888008 -0.428572 -0.252966  1.000000 -0.039252   
v -0.229086 -0.006605 -0.003681 -0.212648  0.049284 -0.039252  1.000000   
w  0.232241 -0.364812 -0.200017 -0.099668 -0.109623 -0.022103 -0.454755   
x  0.120537 -0.063178  0.614534  0.180839  0.199141  0.604393 -0.358633   
y  0.483049 -0.423273 -0.217849  0.667857  0.415312 -0.514500 -0.239365   

          w         x         y  
p  0.232241  0.120537  0.483049  
q -0.364812 -0.063178 -0.423273  
r -0.200017  0.614534 -0.217849  
s -0.099668  0

## Упражнение № 61

Вычислите минимум-максимум для каждой строки `df`.

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))
print("Исходный DataFrame:")
print(df)

min_values = df.min(axis=1)
max_values = df.max(axis=1)
min_max_diff = max_values - min_values
df['min_max_diff'] = min_max_diff

print("\nDataFrame с добавленным столбцом min_max_diff:")
print(df)

Исходный DataFrame:
    0   1   2   3   4   5   6   7   8   9
0  58  94   9  91  82  74  76   3  87  77
1  12  36  13  98  26  24  71  68  59  14
2   6  32  66  64  51   5  37  92  51  81
3   4  94  74  92  32  17  66  14  62  33
4  71  83  45  85  20  94  42  90  17  24
5  33  92  53  53  90  50  81  89  50  97
6  90  39  63  14  51  76  36  44  36  72
7  86  53  90  36  15  25  41  60  55  95

DataFrame с добавленным столбцом min_max_diff:
    0   1   2   3   4   5   6   7   8   9  min_max_diff
0  58  94   9  91  82  74  76   3  87  77            91
1  12  36  13  98  26  24  71  68  59  14            86
2   6  32  66  64  51   5  37  92  51  81            87
3   4  94  74  92  32  17  66  14  62  33            90
4  71  83  45  85  20  94  42  90  17  24            77
5  33  92  53  53  90  50  81  89  50  97            64
6  90  39  63  14  51  76  36  44  36  72            76
7  86  53  90  36  15  25  41  60  55  95            80


## Упражнение № 62

Создайте новый столбец `penultimate`, который содержит второе по величине значение каждой строки `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))
print("Исходный DataFrame:")
print(df)

def second_largest(row):
    return row.nlargest(2).iloc[1]

df['penultimate'] = df.apply(second_largest, axis=1)

print("\nDataFrame с добавленным столбцом 'penultimate':")
print(df)

Исходный DataFrame:
    0   1   2   3   4   5   6   7   8   9
0  57  66  79   3  52  27  33  46  83  57
1  17  43  34  32  30  46  46  96  25  40
2  56  41  44  69  55  68  39  85  58  29
3  33  74   6  12   6  53  28   4  10  10
4  28  56  25  99  62  38  93  55  52  39
5  72  11  37  60  98   6   1  81  25  27
6  78  84  30  75  50   8  43  13  66  21
7  33  27  77  61  94  43  46  72  20  41

DataFrame с добавленным столбцом 'penultimate':
    0   1   2   3   4   5   6   7   8   9  penultimate
0  57  66  79   3  52  27  33  46  83  57           79
1  17  43  34  32  30  46  46  96  25  40           46
2  56  41  44  69  55  68  39  85  58  29           69
3  33  74   6  12   6  53  28   4  10  10           53
4  28  56  25  99  62  38  93  55  52  39           93
5  72  11  37  60  98   6   1  81  25  27           81
6  78  84  30  75  50   8  43  13  66  21           78
7  33  27  77  61  94  43  46  72  20  41           77



## Упражнение № 63

1. Нормализуйте все столбцы `df`, вычитая среднее значение столбца и деля его на стандартное отклонение.
2. Произведите ранжирование всех столбцов `df` таким образом, чтобы минимальное значение в каждом столбце было равно 0, а максимальное — 1.

Не используйте внешние пакеты типа `sklearn`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))
print("Исходный DataFrame:")
print(df)

# Шаг 1: Нормализация столбцов
df = (df - df.mean()) / df.std()
print("\nНормализованный DataFrame:")
print(df)

# Шаг 2: Ранжирование столбцов
df = (df - df.min()) / (df.max() - df.min())
print("\nРанжированный нормализованный DataFrame:")
print(df)

Исходный DataFrame:
    0   1   2   3   4   5   6   7   8   9
0   4  33  90  88  34  59  75  77  15  14
1   1  37  77  61  25  34  48  98  52  30
2  48  33  32  78  26  30  21  77   2  74
3   5  28  65  32  21  37  34  73   1  36
4  43  78  20  47  57  36  79  85  30   9
5  45  11  10  92  98  78  84   4  73  70
6  39  22  78  99  37  94  99  75  63  15
7  84   8  21   7  95  66  72  23  13  93

Нормализованный DataFrame:
          0         1         2         3         4         5         6  \
0 -1.033481  0.080949  1.292870  0.771832 -0.483896  0.200379  0.409946   
1 -1.138138  0.265977  0.881682 -0.061747 -0.771834 -0.854249 -0.596285   
2  0.501478  0.080949 -0.541661  0.463099 -0.739841 -1.022990 -1.602515   
3 -0.998596 -0.150335  0.502124 -0.957071 -0.899807 -0.727694 -1.118034   
4  0.327051  2.162505 -0.921219 -0.493972  0.251946 -0.769879  0.559017   
5  0.396822 -0.936700 -1.237517  0.895325  1.563664  1.001897  0.745356   
6  0.187509 -0.427875  0.913312  1.111438 -0.3879

## Упражнение № 64

Вычислите корреляцию каждой строки `df` с последующей строкой.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 80).reshape(8, -1))

correlations = []
for i in range(len(df) - 1):
    corr = df.iloc[i].corr(df.iloc[i + 1])
    correlations.append(corr)

result_df = pd.DataFrame({
    'Строка 1': df.index[:-1],
    'Строка 2': df.index[1:],
    'Корреляция': correlations
})

print("Исходный DataFrame:")
print(df)
print("\nКорреляции между каждой строкой и последующей строкой:")
print(result_df)

Исходный DataFrame:
    0   1   2   3   4   5   6   7   8   9
0  53  42  82  95   4  12  26  71  73  48
1  70  48  87  92  18  17   3  27  17  18
2  13  43   6  51  97  74  26  76  34  83
3  30  48   1  37  13  80   9  31  55  23
4  90  50  77  90  35  99   2  76  65  10
5  90  21  28  90  11  59  14  80  25  64
6  63  23  45  95  92  54  42  97  95  71
7   3  88   1  72  15  67  94  46  38  71

Корреляции между каждой строкой и последующей строкой:
   Строка 1  Строка 2  Корреляция
0         0         1    0.668047
1         1         2   -0.503795
2         2         3    0.218224
3         3         4    0.500246
4         4         5    0.550061
5         5         6    0.368121
6         6         7   -0.287528


## Упражнение № 65

Замените все значения в обеих диагоналях `df` на 0.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
df
#     0   1   2   3   4   5   6   7   8   9
# 0  11  46  26  44  11  62  18  70  68  26
# 1  87  71  52  50  81  43  83  39   3  59
# 2  47  76  93  77  73   2   2  16  14  26
# 3  64  18  74  22  16  37  60   8  66  39
# 4  10  18  39  98  25   8  32   6   3  29
# 5  29  91  27  86  23  84  28  31  97  10
# 6  37  71  70  65   4  72  82  89  12  97
# 7  65  22  97  75  17  10  43  78  12  77
# 8  47  57  96  55  17  83  61  85  26  86
# 9  76  80  28  45  77  12  67  80   7  63
```

Пример выходных данных:

```python
#     0   1   2   3   4   5   6   7   8   9
# 0   0  46  26  44  11  62  18  70  68   0
# 1  87   0  52  50  81  43  83  39   0  59
# 2  47  76   0  77  73   2   2   0  14  26
# 3  64  18  74   0  16  37   0   8  66  39
# 4  10  18  39  98   0   0  32   6   3  29
# 5  29  91  27  86   0   0  28  31  97  10
# 6  37  71  70   0   4  72   0  89  12  97
# 7  65  22   0  75  17  10  43   0  12  77
# 8  47   0  96  55  17  83  61  85   0  86
# 9   0  80  28  45  77  12  67  80   7   0
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 100).reshape(10, -1))

np.fill_diagonal(df.values, 0)
for i in range(len(df)):
    df.iat[i, len(df) - 1 - i] = 0
print("DataFrame с замененными значениями в диагоналях:")
print(df)

DataFrame с замененными значениями в диагоналях:
    0   1   2   3   4   5   6   7   8   9
0   0  31  75  89  21  46  48  79   7   0
1  19   0  72  19  92   6  36  66   0   2
2   4  32   0  22   3  66  26   0  59  93
3  70  22   2   0  91  92   0   7  50  26
4  17  34  31  54   0   0  59  17  86   4
5  38  75  73  69   0   0  34  54  71  31
6  83  24  74   0  51  92   0  35  94  33
7  97  22   0  40  89  18  41   0  24  22
8  22   0  21  76  99  56  20  25   0  64
9   0  83  50   2  80  88  93   3  17   0


## Упражнение № 66

Из `df_grouped` получите в виде датафрейма группу, относящуюся к `apple`.

Пример входных данных:

```python
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
```

Пример выходных данных

```
    col1      col2  col3
0  apple  0.673434     7
3  apple  0.182348    14
6  apple  0.050457     3
```

In [ ]:
df = pd.DataFrame({
    'col1': ['apple', 'banana', 'orange'] * 3,
    'col2': np.random.rand(9),
    'col3': np.random.randint(0, 15, 9)
})

df_grouped = df.groupby('col1')
print("Исходный DataFrame:")
print(df)
print("\nГруппа, относящаяся к 'apple':")
print(df_grouped.get_group('apple'))

Исходный DataFrame:
     col1      col2  col3
0   apple  0.734270    11
1  banana  0.679657     7
2  orange  0.765651    14
3   apple  0.653946     1
4  banana  0.415187     2
5  orange  0.927821     9
6   apple  0.177425     3
7  banana  0.518324     7
8  orange  0.669498    11

Группа, относящаяся к 'apple':
    col1      col2  col3
0  apple  0.734270    11
3  apple  0.653946     1
6  apple  0.177425     3


## Упражнение № 67

В `df` найдите второе по величине значение `taste` для `banana`.

Пример входных данных:

```python
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
```

In [ ]:
df = pd.DataFrame({
    'fruit': ['apple', 'banana', 'orange'] * 3,
    'rating': np.random.rand(9),
    'price': np.random.randint(0, 15, 9)
})

banana_ratings = df[df['fruit'] == 'banana']['rating']
print("Исходный DataFrame:")
print(df)
print("\nВторое по величине значение 'rating' для 'banana':")
print(banana_ratings.nlargest(2).iloc[-1])

Исходный DataFrame:
    fruit    rating  price
0   apple  0.754737      1
1  banana  0.236182      4
2  orange  0.044415      9
3   apple  0.493545     13
4  banana  0.507152      7
5  orange  0.802987      9
6   apple  0.129861      7
7  banana  0.386753      7
8  orange  0.929249      3

Второе по величине значение 'rating' для 'banana':
0.38675301673312845


## Упражнение № 68

В `df` вычислите среднюю цену `Price` каждого фрукта `Fruit`, сохраняя фрукт как еще один столбец вместо индекса.

Пример входных данных:

```python
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
```

In [ ]:

df = pd.DataFrame({
    'fruit': ['apple', 'banana', 'orange'] * 3,
    'rating': np.random.rand(9),
    'price': np.random.randint(0, 15, 9)
})

print("Исходный DataFrame:")
print(df)
print("\nСредняя цена каждого фрукта:")
print(df.groupby('fruit', as_index=False)['price'].mean())

Исходный DataFrame:
    fruit    rating  price
0   apple  0.326957      1
1  banana  0.914910      0
2  orange  0.456758      2
3   apple  0.736782     11
4  banana  0.020656      0
5  orange  0.826466      5
6   apple  0.581773      2
7  banana  0.351786      6
8  orange  0.397433      2

Средняя цена каждого фрукта:
    fruit     price
0   apple  4.666667
1  banana  2.000000
2  orange  3.000000


## Упражнение № 69

Объединить датафреймы `df1` и `df2` по признакам `fruit-pazham` и `weight-kilo`.

Пример входных данных:

```python
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
```

In [ ]:
df1 = pd.DataFrame({
    'fruit': ['apple', 'banana', 'orange'] * 3,
    'weight': ['high', 'medium', 'low'] * 3,
    'price': np.random.randint(0, 15, 9)
})
df2 = pd.DataFrame({
    'pazham': ['apple', 'orange', 'pine'] * 2,
    'kilo': ['high', 'low'] * 3,
    'price': np.random.randint(0, 15, 6)
})

print("Исходный DataFrame df1:")
print(df1)
print("\nИсходный DataFrame df2:")
print(df2)
print("\nОбъединенный DataFrame:")
print(pd.merge(df1, df2, left_on=['fruit', 'weight'], right_on=['pazham', 'kilo']))

Исходный DataFrame df1:
    fruit  weight  price
0   apple    high      2
1  banana  medium     10
2  orange     low      4
3   apple    high      3
4  banana  medium      7
5  orange     low     13
6   apple    high     13
7  banana  medium     13
8  orange     low     11

Исходный DataFrame df2:
   pazham  kilo  price
0   apple  high     10
1  orange   low      3
2    pine  high     13
3   apple   low      4
4  orange  high      9
5    pine   low     13

Объединенный DataFrame:
    fruit weight  price_x  pazham  kilo  price_y
0   apple   high        2   apple  high       10
1  orange    low        4  orange   low        3
2   apple   high        3   apple  high       10
3  orange    low       13  orange   low        3
4   apple   high       13   apple  high       10
5  orange    low       11  orange   low        3


## Упражнение № 70

Создайте в `df` два новых столбца, один из них — `lag1` (сдвиг столбца `a` вниз на 1 строку) столбца 'a', а другой — `lead1` (сдвиг столбца `b` вверх на 1 строку).

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

    a   b   c   d
0  66  34  76  47
1  20  86  10  81
2  75  73  51  28
3   1   1   9  83
4  30  47  67   4
```

Пример выходных данных:

```python
    a   b   c   d  a_lag1  b_lead1
0  66  34  76  47     NaN     86.0
1  20  86  10  81    66.0     73.0
2  75  73  51  28    20.0      1.0
3   1   1   9  83    75.0     47.0
4  30  47  67   4     1.0      NaN
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns=list('abcd'))
print("Исходный DataFrame:")
print(df)

df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print("\nDataFrame с добавленными столбцами 'a_lag1' и 'b_lead1':")
print(df)

Исходный DataFrame:
    a   b   c   d
0  59  25  93   4
1  30  48  99  71
2  62  12  32  40
3  11  63  37  53
4  92  33   8  79

DataFrame с добавленными столбцами 'a_lag1' и 'b_lead1':
    a   b   c   d  a_lag1  b_lead1
0  59  25  93   4     NaN     48.0
1  30  48  99  71    59.0     12.0
2  62  12  32  40    30.0     63.0
3  11  63  37  53    62.0     33.0
4  92  33   8  79    11.0      NaN


## Упражнение № 71

Получите частоты уникальных значений по всему датафрейму `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
```

In [ ]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns=list('abcd'))

print("Исходный DataFrame:")
print(df)
print("\nЧастоты уникальных значений по всему DataFrame:")
print(df.stack().value_counts().sort_index())

Исходный DataFrame:
   a  b  c  d
0  4  7  7  3
1  7  4  6  5
2  9  3  4  7
3  6  7  6  4
4  6  2  3  4

Частоты уникальных значений по всему DataFrame:
2    1
3    3
4    5
5    1
6    4
7    5
9    1
Name: count, dtype: int64


## Упражнение № 72

Разделите столбец `row` в `df` так, чтобы сформировать датафрейм с 3 столбцами, как показано в примере выходных данных. 

Пример входных данных:

```python
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)
#>                         row
#> 0          STD, City\tState
#> 1  33, Kolkata\tWest Bengal
#> 2   44, Chennai\tTamil Nadu
#> 3  40, Hyderabad\tTelengana
#> 4  80, Bangalore\tKarnataka
```

Пример выходных данных:

```
0 STD        City        State
1  33     Kolkata  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
```


In [ ]:
df = pd.DataFrame(["STD, City\tState",
                   "33, Kolkata\tWest Bengal",
                   "44, Chennai\tTamil Nadu",
                   "40, Hyderabad\tTelengana",
                   "80, Bangalore\tKarnataka"], 
                  columns=['row'])
print(df)

df = df['row'].iloc[1:].str.split('[,\t]', expand=True)
df.columns = ['STD', 'City', 'State']
print("\nРазделённый DataFrame:")
print(df)

                        row
0          STD, City\tState
1  33, Kolkata\tWest Bengal
2   44, Chennai\tTamil Nadu
3  40, Hyderabad\tTelengana
4  80, Bangalore\tKarnataka

Разделённый DataFrame:
  STD        City        State
1  33     Kolkata  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
